### ISSUE TITLE
Checkbutton border

### ISSUE THREAD

**Issue by MorsMortium** [Geballin/gtkTtk#2]
I'm using Breeze-dark-gtk, available as part of https://store.kde.org/p/1197982 . The border lines of checkbuttons are not visible, only the "corners".
This is how it looks:
![Screenshot_20220407_115620](https://user-images.githubusercontent.com/44305161/162173563-d042dfe9-ba63-4584-838b-96537adad67d.png)
And this is how it should:
![Screenshot_20220407_115721](https://user-images.githubusercontent.com/44305161/162173804-c8c8905f-d5e8-4bc9-a3cb-83acde92ace0.png)
My clue is that the buttons have border-radius/they're rounded and gtkTtk can't handle it.

**Comment by Geballin** [comment]
Juste create a 0.8 release which correct it. Please try it and say me if it correct your problems.

**Comment by MorsMortium** [comment]
Yes, it's fixed, thank you!
![Screenshot_20220826_035921](https://user-images.githubusercontent.com/44305161/186800379-13f499cd-d037-49b5-b663-5b5ddbb7e9a0.png)
