### ISSUE TITLE
Scale filled color

### ISSUE THREAD

**Issue by MorsMortium** [Geballin/gtkTtk#3]
I'm using Breeze-dark-gtk, available as part of https://store.kde.org/p/1197982 . The scales don't get filled up to the value they hold.
This is how it looks:
![Screenshot_20220407_120945](https://user-images.githubusercontent.com/44305161/162176097-663112bf-2948-4847-9f3e-d8a741d2ba5a.png)
 And this is how it should:
![Screenshot_20220407_121021](https://user-images.githubusercontent.com/44305161/162176192-e63f191f-7e28-4f58-814e-7770bc398358.png)

**Comment by rdbende** [comment]
Unfortunately this isn't possible with Tk.
