### ISSUE TITLE
Menuitem submenu arrow

### ISSUE THREAD

**Issue by MorsMortium** [Geballin/gtkTtk#5]
I'm using Breeze-dark-gtk, available as part of https://store.kde.org/p/1197982 . Menuitems have the default submenu arrow.
This is how it looks:
![Screenshot_20220407_122531](https://user-images.githubusercontent.com/44305161/162178918-81bb60cd-40f0-4a1b-8055-c9552da0149a.png)
And this is how it should:
![Screenshot_20220407_122754](https://user-images.githubusercontent.com/44305161/162179401-80ce120e-a8a9-4bee-b407-598656f8d9ba.png)

**Comment by rdbende** [comment]
Sadly, menus aren't themable elements.

**Comment by Geballin** [comment]
Like rdbende said, menus aren't Ttk widgets so the arrow can't be changed bu the Ttk theme.
